Fix latest only containing s390x container
generate an error that looks like this:
Error: image name "localhost:37883/hostpath-csi-driver:local"
s already associated with image
"f10f3fe1e406d61ed994cbb67016d07a1bf9e29b173859067302eb8b331722d1":
that name is already in use

But it inadvertently broke the release process by
always removing all the intermediate images this
caused the latest tag to only have s390x since
that is the last architecture to be built.

Signed-off-by: Alexander Wels <awels@redhat.com>